[package]
name = "uitdraai"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
comrak = { version = "0.55.0", default-features = false, features = ["syntect-fancy"] }
directories = "6.0.0"

[features]
default = ["gui"]
gui = []

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
